### PR TITLE
Bump AsyncKeyedLock to 7.0.1

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by Tyrrrz** [comment]
@MarkCiliaVincenti package updates normally go through Dependabot PRs, it's easier to track them that way. Any particular reason you decided to create a PR for this version?

**Comment by MarkCiliaVincenti** [comment]
Actually yes, I forgot to apply. Since AsyncKeyedLocker 7.0.0 there is no need to specify pooling options as defaults of pool size = 20 and initial fill of 1 are applied, the same numbers used by DiscordChatExporter. Thus these settings can be removed now, or you can prefer to leave them there.

**Comment by Tyrrrz** [comment]
Can you please remove them in this PR? Thanks

**Comment by MarkCiliaVincenti** [comment]
> Can you please remove them in this PR? Thanks

Done.

**Pull request merged**
