### PR TITLE
Add message ids in HTML export

### LINKED ISSUE #187: Message ids in html export
@Tyrrrz It would be useful if the messages dumped to html could include their message ids, so that i could programmatically find one given its id. Currently, messages arent even individually wrapped in a div, but it looks like it would be pretty trivial to add a div that wraps each message, and give that div an `id="message_1234567890"`. To be clear, this wouldn't look any different to someone just looking at the rendered html, and is just for if someone wants to be able to find a message programmatically.

I can implement this and create a pull request for it, I just wanted to check with you first to make sure it sounds good to you.

### PR DESCRIPTION
**Pull request by mdiller**
fixes #187

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi,
Can you indent the contents of the div you added?

**Comment by Tyrrrz** [comment]
Also I'd prefer if the attribute was `data-message-id` instead of `id` to separate business logic from view logic

**Comment by mdiller** [comment]
It looks like the indentation is based on the templating language, and that it's actually correct how it is I think?

**Comment by Tyrrrz** [comment]
Yeah, that's a good point. But that means I was doing it wrong before. :)

**Pull request merged**
