### PR TITLE
Dockerize the application

### PR DESCRIPTION
**Pull request by simnalamburt**
Thank you for making the awesome application! Since you have separated the CLI version, macOS and Linux users can use DiscordChatExporter conveniently by Docker!

```bash
docker run "-v${PWD}:/a" simnalamburt/discordchatexporter export -c <CHANNEL ID> -t <TOKEN>
```

###### Reference
- https://hub.docker.com/r/simnalamburt/discordchatexporter/

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Awesome :)
It would be nice if you could integrate it with appveyor.yml so that it gets pushed to docker hub on build.

**Comment by simnalamburt** [comment]
@Tyrrrz If you configure the [Docker Hub automated build](https://docs.docker.com/docker-hub/builds/), there's no need to change the neither appveyor script nor any other script. Give it a try!

**Comment by Tyrrrz** [comment]
Cool! I'll look more into it later, because I don't have much time right now. :)

**Comment by Tyrrrz** [comment]
https://hub.docker.com/r/tyrrrz/discordchatexporter/

**Pull request merged**
