### PR TITLE
[GUI] Make categories collapsible in channel list

### LINKED ISSUE #353: [GUI] Collapsible categories in channel list
I've made some minor modifications to the current source to allow for it...
May request for a pull request if I can get used to how to always match a fork with the current branch....
image

### PR DESCRIPTION
**Pull request by CarJem**
- Added Collapsible Categories for DMs and Servers
- Added To/From Time Pickers to increase UI flexibility of what to export

Closes #353

### CODE REVIEW

**Comment by CarJem** [comment]
I actually just noticed an issue with the sorting in the DMs that causes a potential glitch leading to multiple nested catagories... let me fix it before we merge please.

**Comment by CarJem** [comment]
This should fix the issue... and should be safe to merge

**Comment by Tyrrrz** [comment]
Thanks for PR. Can you please split it in two and make a separate PR for the time selection?

**Comment by CarJem** [comment]
That will take some time....

**Comment by Tyrrrz** [comment]
It appears that the time selection functionality requires changes only to a single file, so can you cut that out from this branch and add it to another branch? If you are unsure how to do it, no worries, I'll do it myself.

**Comment by CarJem** [comment]
I can do it... it's just it might take a little extra time because I do all of the PR Management in Visual Studio... and it's already hard enough to do pull requests because I can't stay up to date if I fork the repo.

Regardless... I can get it done....

**Comment by CarJem** [comment]
Ok I fixed it all and made another PR request!

**Comment by Tyrrrz** [comment]
Thanks!

**Pull request merged**
