### PR TITLE
Added option to export as CSV using CsvHelper package

### PR DESCRIPTION
**Pull request by banCoder**
Added this because I wanted to use it myself.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Forgive my ignorance, but in what scenario would you benefit from a bunch of messages stored in a CSV format?

**Comment by banCoder** [comment]
I wanted to extract conversations in a format suitable for Natural Language Processing and similar analytics.

**Comment by Tyrrrz** [comment]
Hi sorry for late reply again, I've been busy with some stuff. Can you pull the latest upstream and update your pull request since I've changed a lot.

**Comment by Tyrrrz** [comment]
Implemented in #44

**Comment by gdoteof** [comment]
How do get the CSV export from the CLI?  I am using the linux/docker version.  I am able to get an HTML file but can't figure out how to tell it to do csv instead

**Comment by RenanYudi** [comment]
@gdoteof 
`docker run tyrrrz/discordchatexporter export -t TOKEN -c CHANNEL -f Csv`

**Pull request closed without merging**
