### PR TITLE
[CLI] Add command to export all channels across all guilds

### LINKED ISSUE #274: Export all channels from all guilds in a single action
Could you make a feature that allows people to export all channels, in servers, and dms, as a way to archive all chats locally?

### PR DESCRIPTION
**Pull request by wyattscarpenter**
Add a new command to export all Guilds. I don't really write C#, so I just combined the internal logic of GetGuildsCommand.cs and ExportGuildCommand.cs in a way that hopefully works! This addresses issues #274 and #363.

Presumably the syntax for calling this command will have to be added elsewhere, though I imagine it isn't hard.

Closes #274

### CODE REVIEW

**Comment by wyattscarpenter** [comment]
I couldn't really figure out if this will include DMs or not... I imagine people will want to export DMs as well, though perhaps in that case the file should be renamed `ExportAllCommand.cs`

**Comment by Tyrrrz** [comment]
Thanks for the pr, @wyattscarpenter.
It looks like your code doesn't compile. You need to inherit from `ExportMultipleCommandBase` not `TokenCommandBase`.
I think there should be also a switch that dictates whether to include DMs or not (`--include-dm`) and the name of the command can be changed to `exportall`.

**Comment by wyattscarpenter** [comment]
It inherits the right class now.

**Comment by wyattscarpenter** [comment]
Now it should include the DMs by default, and has a flag to exclude them.

**Comment by Tyrrrz** [comment]
Thanks!

**Pull request merged**
