### PR TITLE
Add "%r" placeholder to wrap parts of the path

### LINKED ISSUE #1123: Make template tokens work properly for export paths of threads
### Version

v2.40.4

### Flavor

GUI (Graphical User Interface), CLI (Command-Line Interface)

### Platform

Any

### Export format

_No response_

### Steps to reproduce

Export threads and use template tokens in the path

### Details

Path parameters need to be rethought with threads because DCE uses the same given path for both channels and threads. That messes with threads. Let's look at the following example:

`\\%G\\%P – %T\\%p – %C.html`

It essentially means:

`Server\\Category\\Channel.html`

This should result in the following structure:

```
Server name
|
|-- Category name 1
|     |
|     |-- Channel name 1 
|     |-- Channel name 2
|     |-- Thread of channel 1
```

If I export a channel, the term gets evaluated properly.

However, if I export a thread, the term doesn't get evaluated properly. Here's why:

`%P – %T` will evaluate to the parent channel, because that is "the thread's category", instead of using the server-level category.

Ultimately, this means that you will end up with something like this:

```
Server name
|
|-- Category name 1
|     |
|     |-- Channel name 1 
|     |
|     |-- Channel name 2
|
|-- Channel name 1
      |
      |-- Thread of channel 1
```

Possible solutions would be:

- Let the user pass separate paths for threads and channels
- Just evaluate the given path for channels. For threads, evaluate the same term for the parent channel and put the threads inside whatever folder their parent channel is in.

The first option would be more flexible, and clearer to the user. However, we'd need two more parameters: one for the name of a parent channel and one for a thread's name.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

### PR DESCRIPTION
**Pull request by Paullitsch**
…be set recursively. #1123. e.g.: "\\%G\\%r%P – %T%r\\%p – %C.html"

Closes #1123

### CODE REVIEW

**Comment by Paullitsch** [comment]
Sorry - this lacks a little description.

The idea was to evaluate some parts of the export path-schema recursively (iterating through the parent channels).
See #1123 - here it was discussed that we can not use "%T" to put Threads into the same folder as the owner Channel. 
With this recursive call you can achieve this now because the code will update the output path as the following: 

Inital path pattern: \%G\%P – %T\%p – %C.html
updated path pattern: \%G\%r%P – %T%r\%p – %C.html

so on the first iteration will find the regex group: %P – %T
the value of the group will be forwarded again to "FormatPath" with the parent-channel as context - which than look like: 
_\%G\{Channel.Parent.Parent.Position} - {Channel.Parent.Parent.Name}\%p – %C.html_

the updated path will than be used to replace the leftover placeholder values:
_\{Guild.Name}\{Channel.Parent.Parent.Position} - {Channel.Parent.Parent.Name}\{Channel.Position} – {Channel.Name}.html_

After looking through it today again this could be more optimized but i think the conceptional idea / solution is still fine

**Comment by CanePlayz** [comment]
Thanks for the thorough explanation, interesting approach. Would this mean that with only one path parameter you could end up with such a result?

```
Server name
|
|-- Category name 1
      |
      |-- Channel name 1 
      |
      |-- Channel name 2
      |
      |-- Channel name 1
            |
            |-- Thread of channel 1
```

It would after all still limit the options of how you can format the parent channel part since its structure would be inherited from the category structure, but I don't think that would be an issue as most people have these symmetrical approaches anyways.

**Comment by Tyrrrz** [comment]
@CanePlayz can you comment whether this PR fully addresses #1123, as reported by you?

**Comment by CanePlayz** [comment]
> This puts the threads into the same folder as the parent channel with the thread having the same naming structure as its parent channel. Rather than creating another folder inside the same directory as that of the parent channel, which is what I had imagined in the initial issue and above.

Unfortunately not. I guess it'd still be an enhancement, but:

This new method puts the thread files into the same folder as the parent channel files with the thread having the same naming structure as its parent channel. What I had imagined in the initial issue was creating another folder inside the same directory as that of the parent channel where all the threads would be stored (you can see that desired structure above).

**Comment by CanePlayz** [comment]
However, a possible solution to this could be introducing new parameters that are thread-exclusive (meaning if the channel being processed is a normal one, they are just being ignored, but if the channel is a thread, they are indeed being resolved to for example the name of the parent channel or its position.

**Comment by CanePlayz** [comment]
I've implemented these two parameters now. Should I open a PR for it?

**Comment by Tyrrrz** [comment]
I think this is an interesting design, but I don't want to make placeholders too complicated. Adding parametrized recursion opens the door to a fully programmatic DSL inside filename templates, which could definitely be useful, but not necessarily something I want to support. I think we should offer basic templating support, but mostly defer to bulk renaming tools to let the user establish more tailored file structures.

**Pull request closed without merging**
